# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
                ('size', models.IntegerField()),
                ('parking_space', models.BooleanField()),
                ('no_of_bed', models.IntegerField()),
                ('no_of_bath', models.IntegerField()),
                ('floor_no', models.IntegerField()),
                ('lift', models.BooleanField()),
                ('cctv', models.BooleanField()),
                ('generator', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('service_charge', models.IntegerField(default=0)),
            ],
            bases=('Rental.rental',),
        ),
        migrations.CreateModel(
            name='ConventionCentre',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
                ('size_of_floor', models.IntegerField()),
                ('no_of_floor', models.IntegerField()),
                ('human_capacity', models.IntegerField()),
                ('catering_system', models.BooleanField()),
                ('parking_space', models.IntegerField()),
                ('open_space', models.BooleanField()),
            ],
            bases=('Rental.rental',),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
            ],
            bases=('Rental.rental',),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
                ('no_of_roommate', models.IntegerField()),
                ('available_roommate', models.IntegerField()),
                ('rent_with_meal', models.IntegerField(blank=True, null=True)),
                ('bed', models.BooleanField()),
                ('table', models.BooleanField()),
                ('chair', models.BooleanField()),
                ('water_purifier', models.BooleanField()),
            ],
            bases=('Rental.rental',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
                ('size', models.IntegerField()),
            ],
            bases=('Rental.rental',),
        ),
        migrations.CreateModel(
            name='Sublet',
            fields=[
                ('rental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rental.Rental')),
                ('total_roommate', models.IntegerField()),
                ('available_roommate', models.IntegerField()),
                ('family', models.BooleanField()),
                ('bed', models.BooleanField()),
                ('table', models.BooleanField()),
                ('chair', models.BooleanField()),
                ('water_purifier', models.BooleanField()),
            ],
            bases=('Rental.rental',),
        ),
        migrations.AlterField(
            model_name='rental',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
