# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0006_auto_20171104_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventioncentre',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
